No bridge support
camptocamp/terraform-docker-k3s pull request #12
Opened 2021-04-22 21:19 UTC by pburgisser

When there is no bridge (on mac), the wait_for_cluster cannot reach the API as it can't contact the pod IP.
In conjunction with port publishing, terraform can then access the master.

2021-04-22 21:23 UTC, pburgisser commented
cc @mcanevet

2021-04-23 18:49 UTC, mcanevet commented
Hmmm... I'm not in favor of adding a `base_domain` variable.
Maybe we should find a way to either ignore wait for cluster or use localhost when the port is published.

2021-04-23 19:00 UTC, pburgisser commented
We must be able to change replace the pod IP by something in the kubectl output that is also used when deploying ArgoCD.
Maybe when the network_name isn't "bridge" we replace the container IP by localhost? or we can rename the variable by something like "k8s_master_hostname" ?

2021-04-24 06:41 UTC, mcanevet commented
Maybe a `cluster_endpoint` variable that defaults to `https://<container_ip>:6443` but could be overridden.

2021-04-24 06:43 UTC, mcanevet commented
Or maybe a `tls_san` variable that we would also pass as argument to the server : https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#listeners

2021-04-24 06:57 UTC, pburgisser commented
cluster_endpoint sounds good. When set we add to the SAN.
What do you think?

2021-04-24 18:18 UTC, mcanevet commented
Yes that sounds good. The tricky part would be to extract the hostname from the endpoint, but it feasible.

2021-04-26 06:04 UTC, pburgisser commented
@mcanevet done.
I'm not sure the tls_san is necessary as it works this way already.
I named the variable api_endpoint as cluster_endpoint is already an output.

2021-04-26 06:18 UTC, mcanevet commented
@pburgisser i'm pretty sure that if you don't set `tls-san`, the generated certificate will not contain the URL you pass as API endpoint.
Regarding the variable name, I think we should keep  ̀cluster_endpoint` also for input as it's the same thing. The only thing you have to do is to return the `cluster_endpoint` you passed as input if you override it.

2021-04-26 07:24 UTC, pburgisser commented
@pburgisser There you go :)

2021-04-26 07:41 UTC, mcanevet requested changes

2021-04-26 07:41 UTC, mcanevet commented on outputs.tf
> +  value = format("https://%s:6443", coalesce(var.cluster_endpoint, docker_container.k3s_server.ip_address))
`local.cluster_endpoint`?

2021-04-26 07:43 UTC, pburgisser commented on outputs.tf
> +  value = format("https://%s:6443", coalesce(var.cluster_endpoint, docker_container.k3s_server.ip_address))
Damn it, I missed this guy

2021-04-26 08:06 UTC, merged